### ISSUE TITLE
Update URL of production deploy to directory.platform.coop

### ISSUE THREAD

**Issue by greatislander** [platform-coop-toolkit/coop-map-directory-index#128]
## Is your feature request related to a problem? Please describe.

Currently the production deploy and database is at https://demo.directory.platform.coop.

## Describe the solution you'd like

It should be changed to https://directory.platform.coop.

## Describe alternatives you've considered

Not applicable.

## Additional context

Not applicable.

**Comment by gtirloni** [comment]
Could this be done ASAP or do we have to plan and notify stakeholders?

**Comment by greatislander** [comment]
I believe this could be done ASAP as long as we can add a 301 redirect for the old URL.
