### ISSUE TITLE
Review account login & registration templates

### ISSUE THREAD

**Issue by erictheise** [platform-coop-toolkit/coop-map-directory-index#15]
Account creation & login using email and password is functional. The most-frequently involved templates make use of Pinecone styling and the most-frequently involved email subjects and messages have been updated to reflect their use in the Platform Coop Directory.

All of the templates related to this issue are in [templates/account/](https://github.com/platform-coop-toolkit/coop-map-directory-index/tree/master/templates/account). Templates showing a commit of `chore: commiting stock templates…` have not yet been touched.

That said, the templates still contain stock page titles and language (the spelling "e-mail" was already antiquated when they wrote this library, what were they thinking?).
 
This issue is for collecting feedback on account creation, password resets, login/logout using email+password. They can be flow-, style-, or content-related.

(This issue was originally opened in the context of `django-registration`, which I've replaced with `django-allauth`.)

**Comment by jhung** [comment]
@erictheise I've started to look at this and can give you feedback later this week.

**Comment by jhung** [comment]
@erictheise I was looking at these pages. While I could make comments about what I see, I assume there will be designs / wires for these pages eventually? Perhaps it's better that I hold off making comments since it may all change anyway. Thoughts?

**Comment by erictheise** [comment]
Okay with me to delay review until later @jhung, thanks for starting in on it.

**Comment by erictheise** [comment]
Excerpting Trebor's email from 14 May –

```
We are enrolling some 250 learners in our Platform Co-op Now course with Mondragon.
```
 
– so it's time to review the sign up flow.
