### ISSUE TITLE
Profile creation Cancel dialog

### ISSUE THREAD

**Issue by dayotte** [platform-coop-toolkit/coop-map-directory-index#27]
https://files.inclusivedesign.ca/s/rJUZSV6Kq1uhU4i

**Comment by erictheise** [comment]
![image](https://user-images.githubusercontent.com/317680/80179450-6ea36c00-85b5-11ea-898a-f3292d5c9560.png)

**Comment by erictheise** [comment]
![image](https://user-images.githubusercontent.com/317680/80180084-cc848380-85b6-11ea-89e0-3ff93b967a7f.png)

This is a modal dialogue so `Next` and  `Cancel` are unavailable.

"all of your information" sounds extreme and is not accurate as email address and password is still preserved.

**Comment by erictheise** [comment]
Also, @greatislander, might have asked this in IRC but what's the pattern for wiring actions into this dialogue?

**Comment by greatislander** [comment]
@erictheise Still need any assistance from me with this?

**Comment by erictheise** [comment]
I haven't done any additional work on this @greatislander. The "No, return…" option needs nothing; clicking or `esc` clears the modal and leaves you where you were before `Cancel`ing.

For the "Yes, exit…", I already expressed a concern that "delete all info" could be taken to mean  "delete my account" but in any case I need to know where to send people when they bail out @dayotte. Back to the homepage? Some interstitial page?

@greatislander what I was wondering from you or @jhung was what's the preferred method for getting to that new page. Is there a page redirect built into Pinecone? Use `window.location`? Wrap this in a form and have Django redirect on submit? It's part Pinecone question, part "do it without JavaScript" question. Hope that clarifies, thanks.

**Comment by dayotte** [comment]
> For the "Yes, exit…", I already expressed a concern that "delete all info" could be taken to mean "delete my account" but in any case I need to know where to send people when they bail out @dayotte. Back to the homepage? Some interstitial page?

@erictheise Cancel should take user back to home page

How about this for more clearly communicating what will be lost
![Cancel v2](https://user-images.githubusercontent.com/6207009/81019750-263d4700-8e1c-11ea-8f6c-29e75c9365ad.png)

**Comment by dayotte** [comment]
> For the "Yes, exit…", I already expressed a concern that "delete all info" could be taken to mean "delete my account"

How about this
![Cancel v3](https://user-images.githubusercontent.com/6207009/81020982-f17ebf00-8e1e-11ea-8927-e291a0ef40b4.png)

**Comment by dayotte** [comment]
@erictheise thinking it might be good to have the option to save profile info partway through and return later, is that feasible? Maybe not MVP? We would need a way to indicate the existence of an incomplete profile under "My profiles", which I can put some thought to.
![Cancel v2](https://user-images.githubusercontent.com/6207009/81021084-2ee34c80-8e1f-11ea-9f0a-efdaedee6c87.png)
