### ISSUE TITLE
Include usage data in tools API

### ISSUE THREAD

**Issue by greatislander** [platform-coop-toolkit/coop-map-directory-index#30]
## Is your feature request related to a problem? Please describe.

We need to be able to show how many co-ops have listed a tool as something that they use:

![card](https://user-images.githubusercontent.com/605361/80123529-403d7680-854c-11ea-9408-02c35f49b732.png)

## Describe the solution you'd like

We should reflect the relationship between tools and co-ops in the tools API endpoint: an integer value, with a property name like `usecount`, which indicates how many co-ops have indicated that they use the tool.

## Describe alternatives you've considered

Not applicable.

## Additional context

Full disclosure: I haven't dug deeply into the models to see if there's anything in place yet, but I wanted to capture this need.

**Comment by erictheise** [comment]
There's nothing in place yet.

[Some mocks](https://github.com/platform-coop-toolkit/coop-map-directory-index/issues/7#issuecomment-603465867) indicated that we'd collect tool use from individuals, too. I don't know if this idea is still in play; @dayotte? @cherylhjli?

If it is, the API would need to return something flat like `usecount_orgs` and `usecount_inds` or an object, such as:

```
usecount: {
  orgs: 53
  inds: 17
}
```

**Comment by dayotte** [comment]
@erictheise we have decided to limit listing of tools to co-operatives

**Comment by erictheise** [comment]
`use_count` is now part of the Tool object and is exposed via the API, e.g,

```
    {
        "name": "Trello",
        "description": "A project management tool that allows you to make cards and categorize them in a kanban style interface. You are able to add further project management elements to your cards, such as assignees, due dates, checklists, and comments.",
        "url": "https://trello.com/",
        "license": null,
        "pricing": "Free",
        "niches": [
            {
                "name": "Collaboration - Project management",
                "description": ""
            }
        ],
        "languages_supported": [
            {
                "culture_code": "en",
                "iso_name": "English"
            }
        ],
        "sectors": [],
        "use_count": 0
    }
```

**Comment by greatislander** [comment]
Thanks @erictheise!
