### ISSUE TITLE
Implement MVP for site navigation and information architecture

### ISSUE THREAD

**Issue by dayotte** [platform-coop-toolkit/coop-map-directory-index#31]
![Directory Site Nav](https://user-images.githubusercontent.com/6207009/80395506-28296800-8868-11ea-9c85-e2b23a061e86.png)

**Comment by erictheise** [comment]
@dayotte, a few questions.

1. you've been using the Canadian/British spelling _organisation_ for the past few iterations so I'm confused about why it's not _My Favourites_ in the nav bar. It has the "u" in your red notes. I'd suspect that the New School would prefer American English but if all these elements are going to be translated sometime down the road being consistent now will help that effort.
2. we've been using sentence case up until now. Unless _Favo[u]rites_ has special meaning in the interface it looks out of place capitalized to me.

My thoughts on the remarks in red.

1. all the things you have under `Explore ^` probably require the same queries as what underlies the filtering. What's needed are flows, mocks for search forms and results pages, pagination parameters for the results pages.
2. seems premature to worry about favoriting profiles when we don't yet have profiles. If favoriting is essentially bookmarking for a registered user then it should be fairly easy to implement. If favorites are tallied up across all users and displayed for others to see… that's complicated for design, implementation, and really should only be undertaken after stakeholder discussions about whether or not the system should support popularity contests and the gaming it brings along.
3. seems extremely premature to worry about saved searches when we don't yet have profiles to search and have no spec for search (what fields are searched? categorical or full text? which fields? how forgiving should we be about misspellings?) Saved search seems unminimal to me.
4. saving favorites & saved searches in browser local storage. You and I have already discussed this but I'll put my comments on the record. 

    I'm not a fan because the action implies a level of permanence not afforded by the technology. It's appropriate for the Resource Library because it has no accounts and it's the only way it could be implemented. 

    Who explains to the Directory user that the favorites they saved on their phone aren't available on their laptop? What happens to the totals when a user never returns to the system; do they expire somehow? Do we keep adding to the total favorites for a co-op when an anonymous user deletes their local storage and favorites it again? What if they write a malicious little loop to do that?

    What do we do if a registered user forgets to log in, saves to local storage, then does log in. Display both favorite lists? Offer to merge the ones in local storage to the database? This is subtle development for proven, mature products.

    If feedback via crits says favoriting is critical to the success of the platform then people should be encouraged to create accounts and it should be added to the [list of reasons why a person might or might not care to create an account](https://github.com/platform-coop-toolkit/coop-map-directory-index/issues/4).

**Comment by erictheise** [comment]
@greatislander, @jhung, I don't know if there's a Pinecone way to
- align the search field in the nav bar left to the pinecone logo
- have it expand to the right for a user who's not logged in

**Comment by dayotte** [comment]
1. I'd suspect that the New School would prefer American English but if all these elements are going to be translated sometime down the road being consistent now will help that effort.
> 
2. we've been using sentence case up until now. Unless _Favo[u]rites_ has special meaning in the interface it looks out of place capitalized to me.
> 
@erictheise an oversight, thanks for identifying, let's use American English for all and sentence case in the nav (My favorites, My profile etc)

**Comment by dayotte** [comment]
>     1. all the things you have under `Explore ^` probably require the same queries as what underlies the filtering. What's needed are flows, mocks for search forms and results pages, pagination parameters for the results pages.
@erictheise I hoped that was the case (same queries as filtering), am working on those flows

**Comment by erictheise** [comment]
Adjusted spellings and case in a575fe6.

**Comment by dayotte** [comment]
Updated site map to remove Explore option as we decided it did not add significant functionality over filtering. Also rename "Settings" to "Account", and allow Favoriting profiles only when signed into an account.
![Site Map](https://user-images.githubusercontent.com/6207009/81981953-e4638c00-95e5-11ea-9739-7f88e4b998cc.png)

**Comment by dayotte** [comment]
@greatislander updated site map:
![Site Map](https://user-images.githubusercontent.com/6207009/87093605-52958b00-c1f2-11ea-92a8-c3f789215661.png)

**Comment by greatislander** [comment]
This is done.
