### ISSUE TITLE
Implement searching functionality

### ISSUE THREAD

**Issue by dayotte** [platform-coop-toolkit/coop-map-directory-index#36]
Suggested content to be searched:
- Profile names
- Descriptions/bios
- Tags/filters

**Comment by dayotte** [comment]
![Home Page Mobile - Filter, Search, Map Summary](https://user-images.githubusercontent.com/6207009/82380058-bbc00580-99dc-11ea-87e1-7c4ad37d5e1e.png)

![Home Page - Filter, Search, Map Summary](https://user-images.githubusercontent.com/6207009/82380070-c1b5e680-99dc-11ea-837f-8d59da9155c7.png)

**Comment by greatislander** [comment]
@erictheise I am hesitant to touch this until you have addressed location-based search. Not sure where that is in the work you're doing.
