### ISSUE TITLE
Design and implement flow for a co-op to add tool(s) to directory profile 

### ISSUE THREAD

**Issue by dayotte** [platform-coop-toolkit/coop-map-directory-index#37]
Users who have an account/are logged in have the option to select "My co-op uses this" tool from the Tool Library. In that case, the tool should be added to their co-op's profile in the directory. This means we will need some way to confirm that they have access to a co-op profile, not just an individual profile, and/or a way to indicate which co-op profile they want to attach the tool use to (and then have it vetted by whomever "owns" that co-op profile).

Also, from the directory side, we want co-ops to be able to add tools they use to their profile (to either search for and choose tools that are listed in the Library, or to go to the Library and add them if they are not already there). Mockups for this flow attached.

FYI @cherylhjli

**Comment by dayotte** [comment]
![Add Tool Flow](https://user-images.githubusercontent.com/6207009/81328037-1b1f2c80-9051-11ea-9f4a-7397a561812f.png)
![Add existing tool](https://user-images.githubusercontent.com/6207009/81328044-1d818680-9051-11ea-836a-424117b6d82d.png)
![Add new tool](https://user-images.githubusercontent.com/6207009/81328051-1fe3e080-9051-11ea-99cb-b3c3faed263a.png)

**Comment by dayotte** [comment]
@greatislander were you wanting to add an issue different than the one described here? i.e. do we need a separate issue for adding tools to Tool Library?

**Comment by greatislander** [comment]
@dayotte We can use this issue but it would be good to drop in the flows for creating a tool so I can reference them from here. Thanks!

**Comment by dayotte** [comment]
@greatislander The flow for submitting a new tool to to the Tool Library, from the Directory, is defined by the following.

In the PC_Directory XD file, the _DK/Org profile/Edit/Tools/Add2_ screen shows the "Submit new tool" button on the Tool tab of the Editable view of the Co-op profile. From there, the submit new tool flow is defined in the [Figma Tool Library - Wireframes file](https://www.figma.com/file/qQOmueomYfwetpIuQrFWmZ/Tool-Library-Wireframes?node-id=2196%3A20817) on page 3.0 Share your tools (& add a tool).

**Comment by greatislander** [comment]
@dayotte I think the two methods you mention are sufficient. Thanks!
