### ISSUE TITLE
Create a Mapbox account for the site

### ISSUE THREAD

**Issue by erictheise** [platform-coop-toolkit/coop-map-directory-index#43]
Current implementation uses one of @erictheise's keys for the map tiles.

Create a Mapbox account that resides with New School or IDRC.
Update the key in the `.env` file wherever production resides at the time.

**Comment by greatislander** [comment]
@erictheise To clarify, where does the Mapbox key go in `.env`? I see what appears to be a publishable key in the JavaScript file but nothing in `.env`.

**Comment by gtirloni** [comment]
Default public token for new account added to 1Password (Platform Co-op).
