### ISSUE TITLE
Design & implement "full profile" for organizations

### ISSUE THREAD

**Issue by erictheise** [platform-coop-toolkit/coop-map-directory-index#6]
Our [wireframe](https://www.figma.com/file/tXFtpKPWuGUFrotFsXshZq/Directory-explorations_DA?node-id=174%3A4) features lots of links to __View full profile__. I think we'll need one design for organizations and one for individuals. This issue is for organizations.

This is a moving target as the data model and API are still in the early stages but data will be delivered in the GeoJSON format which has a `geometry` section and a `properties` section that we'll fill, e.g.

```
{       
    "type": "Feature",
    "geometry": {
        "type": "Point",
        "coordinates": [
            -73.9441579,
            40.6781784
        ]       
    },      
    "properties": {
        "name": "Ampled",
        "description": "Monthly recurring support for music artists, directly from listeners",
        "category": "platform co-op", 
        "type": "cooperative",
        "sectors": [
            "Art",  
            "Finance"
        ],      
        "address": "",
        "city": "Brooklyn",
        "state": "New York",
        "postal_code": "",
        "country": "US",
        "url": ""
    }       
} 
```

This is being expanded to include social media handles/links, additional contact info, and vital statistics such as number of employees, year founded, and measures of impact. I'd like the card to include a small inset map showing the location zoomed in, maybe 1km square?

It'd be great to have a basic layout to start iterating from @dayotte. Let's track it here.

**Comment by erictheise** [comment]
This Figma rookie just discovered the [Profile Page Explorations](https://www.figma.com/file/tXFtpKPWuGUFrotFsXshZq/Directory-explorations_DA?node-id=273%3A4) and sees that a lot has already been thought through. Catching up with these designs.

**Comment by erictheise** [comment]
@dayotte more data is available from the Survey. [NeedsMap Coop](https://demo.directory.platform.coop/organizations/1503) exhibits much of this.

The wireframes show _Years in operation_ as a field throughout and I'm not sure what you're envisioning with this; that value would become obsolete every year. The correct data to collect is _Date founded_ and while many survey respondents only know the year and I can code for that, more than one know the exact date and I would encourage people to enter that if they do. _Years in operation_ may be calculated from the current time and while I have not yet implemented this I would suggest both profile input and display show _Date founded_ with _Years in operation_ in parens.

For data we collect in `textarea`s I'm displaying _lorem ipsum_ if we have none or the actual text if we do. For organizations that would be the _Description_ and _Notes_ fields.

**Comment by dayotte** [comment]
@erictheise intention is to use number of years in operation as one way to communicate how established a coop is. Collecting Date Founded and calculating years in op from that sounds good to me. Requiring at least a year entry for Date Founded, with day and month optional also sounds reasonable.

**Comment by dayotte** [comment]
@erictheise I wonder if we shouldn't break these out into separate issues...but I'm attaching the latest profile wireframe (no Notes field, no Resources field, includes Description, Members, Challenges, Goals, Tools, Contact, Social Media) - see also Profile Pages Wires page in Figma file
https://www.figma.com/file/tXFtpKPWuGUFrotFsXshZq/Directory-Wireframes_DA?node-id=536%3A245
![Coop Profile Page Mar 24 2020](https://user-images.githubusercontent.com/6207009/77463576-106f4780-6dc3-11ea-8aa6-0c269b4d3d15.png)

**Comment by erictheise** [comment]
Thanks for posting the wireframe @dayotte. Not sure what you mean by "break these out into separate issues". Each rendered field? Each section?

**Comment by erictheise** [comment]
Some general questions in the meantime @dayotte.

The section after `Languages:` and before `Description`. Is this better rendered as an html `table` or as a sequence of Pinecone `badges`? Currently it's `badges` but only because it's the better visual match to the wireframe.

And when we have no data do you suggest we suppress the row or populate the value with "Unknown" or some other placeholder?

**Comment by erictheise** [comment]
@dayotte, it's __Members:__, __Contact:__, and __Follow:__ (w/colons) while other sections don't have colons; I think we should be consistent and have a slight preference for not using a colon but will follow your recommendation.

**Comment by erictheise** [comment]
Last question in this batch, @dayotte, for all sections, when we have no data, do we suppress the whole section or use "Unknown" or other placeholder? Similar to the [Sector/Type/Years…](https://github.com/platform-coop-toolkit/coop-map-directory-index/issues/6#issuecomment-603976124) question above.

**Comment by dayotte** [comment]
> Thanks for posting the wireframe @dayotte. Not sure what you mean by "break these out into separate issues". Each rendered field? Each section?
@erictheise I was thinking separate issues for each of your questions, but let's just keep it to this one issue for now. I think as we get further it might get out of hand and we may need separate issues

**Comment by dayotte** [comment]
> Some general questions in the meantime @dayotte.
> 
> The section after `Languages:` and before `Description`. Is this better rendered as an html `table` or as a sequence of Pinecone `badges`? Currently it's `badges` but only because it's the better visual match to the wireframe.
> 
> And when we have no data do you suggest we suppress the row or populate the value with "Unknown" or some other placeholder?

@erictheise since they are not badges a table would be better. For now let's populate each row with "N/A" where there is no data. My thinking is that it will be an indication to users that this data may exist in other profiles in the directory (rather than assuming that a directory with little data is the norm). We can get co-design feedback on this.

**Comment by dayotte** [comment]
> @dayotte, it's **Members:**, **Contact:**, and **Follow:** (w/colons) while other sections don't have colons; I think we should be consistent and have a slight preference for not using a colon but will follow your recommendation.

@erictheise sorry and thanks for catching that, agree that no colons is best

**Comment by dayotte** [comment]
> Last question in this batch, @dayotte, for all sections, when we have no data, do we suppress the whole section or use "Unknown" or other placeholder? Similar to the [Sector/Type/Years…](https://github.com/platform-coop-toolkit/coop-map-directory-index/issues/6#issuecomment-603976124) question above.

@erictheise as above, let's put N/A for now and get co-design feedback on this

**Comment by erictheise** [comment]
Thanks @dayotte. My concern specifically with "[N/A](https://en.wikipedia.org/wiki/N/a)" is that it can mean "not applicable", "not available", or "no answer". In the current context it's always "not available" or "no answer" and never "not applicable".

I'd favor "Unknown" or spelling out "Not available".

"Not available" or "No answer" to me suggests that maybe the respondent has chosen not to answer but at this stage most of them haven't been given a fair opportunity.

**Comment by erictheise** [comment]
This is probably the most complicated and important flow in the Directory. Implementing the [five step User profile](https://github.com/platform-coop-toolkit/coop-map-directory-index/issues/7) took the better part of a week and there hasn't been an update here to the mocks for this flow in almost two months.

**Comment by dayotte** [comment]
mockups for co-ops:
![Coop Basic Info Step 1](https://user-images.githubusercontent.com/6207009/82360830-d08da080-99be-11ea-916e-631ebfb1151d.png)
![Coop Basic Info Step 2](https://user-images.githubusercontent.com/6207009/82360842-d5525480-99be-11ea-8a0e-b38203b892c2.png)
![sector dropdown](https://user-images.githubusercontent.com/6207009/82360880-e3a07080-99be-11ea-8f26-3a8bccb3191f.png)
![Co-op Org Subcategories_Step 3](https://user-images.githubusercontent.com/6207009/82360861-dd11f900-99be-11ea-9223-5a09b146331b.png)
![Coop Profile Private Editable View](https://user-images.githubusercontent.com/6207009/82360897-eb601500-99be-11ea-9ccb-f93179ec3a79.png)

**Comment by cherylhjli** [comment]
Updated screens for section-based editing:

Coop profile "overview" page:
https://xd.adobe.com/view/0bee1f78-8335-4b41-75fa-e85183937d3c-7ddf/screen/93d9ec7f-61d9-4d2a-ac2d-de447a95596b/DK-Org-profile-Filled-Out-View-only-Overview-1

Edit "overview" page:
https://xd.adobe.com/view/0bee1f78-8335-4b41-75fa-e85183937d3c-7ddf/screen/e4320036-d412-4972-b699-f55e921ff4b2/DK-Org-profile-Minimal-Edit-1
https://xd.adobe.com/view/0bee1f78-8335-4b41-75fa-e85183937d3c-7ddf/screen/8595ec27-03a0-4d31-b802-c40daa3f19da/DK-Org-profile-Minimal-Edit-2

Coop profile "contact" page:
https://xd.adobe.com/view/0bee1f78-8335-4b41-75fa-e85183937d3c-7ddf/screen/fb81dc86-6192-4f05-a1bf-fa2b668952eb/DK-Org-profile-View-only-Contact-1

Edit "contact" page:
https://xd.adobe.com/view/0bee1f78-8335-4b41-75fa-e85183937d3c-7ddf/screen/80206e82-0a80-47b9-8878-39ffef3ab6d0/DK-Org-profile-Minimal-Edit-3
https://xd.adobe.com/view/0bee1f78-8335-4b41-75fa-e85183937d3c-7ddf/screen/0ad495ba-6982-4605-9144-36f86882b96d/DK-Org-profile-Minimal-Edit-4

Member tab (ignore top header area, that's not updated)
_Mobile versions of these are in the XD file._
https://xd.adobe.com/view/0bee1f78-8335-4b41-75fa-e85183937d3c-7ddf/screen/683f5025-0dca-4d8c-bf35-a80d1e3f4692/DK-Org-profile-Edit-Members-Add1
https://xd.adobe.com/view/0bee1f78-8335-4b41-75fa-e85183937d3c-7ddf/screen/40d27ba7-4c3d-45d7-87d9-17bf8de37398/DK-Org-profile-Edit-Members-Add2
https://xd.adobe.com/view/0bee1f78-8335-4b41-75fa-e85183937d3c-7ddf/screen/b7de6c46-29cd-42fa-b6b0-4a76478b50b0/

Tool tab (ignore top header section, that's not updated)
_Mobile versions of these are in the XD file._
https://xd.adobe.com/view/0bee1f78-8335-4b41-75fa-e85183937d3c-7ddf/screen/dade1aa6-4838-4e8e-a954-cf0c259181e6/DK-Org-profile-Edit-Tools
https://xd.adobe.com/view/0bee1f78-8335-4b41-75fa-e85183937d3c-7ddf/screen/7245cfad-28a5-4011-a5d5-0574aae372f8/DK-Org-profile-Edit-Tools-Add1
https://xd.adobe.com/view/0bee1f78-8335-4b41-75fa-e85183937d3c-7ddf/screen/35e91c4e-6dbb-41f4-993f-98e2bb25180d/DK-Org-profile-Edit-Tools-Add2
https://xd.adobe.com/view/0bee1f78-8335-4b41-75fa-e85183937d3c-7ddf/screen/7eaa4bdd-0db2-4441-a470-2834fa1dac40/DK-Org-profile-Edit-Tools-Add-Successful
