### ISSUE TITLE
Set up a separate dev deploy

### ISSUE THREAD

**Issue by greatislander** [platform-coop-toolkit/coop-map-directory-index#68]
Currently, the database at https://demo.directory.platform.coop contains our production data. For development it would be good to have a separate deployed version (https://dev.directory.platform.coop) that is less critical. It also makes sense to deploy code from `master` to the production site and from `dev` to the development site, as we do for other Platform Co-op projects.

**Comment by greatislander** [comment]
@gtirloni I've created a `dev` branch.

@erictheise I am leaving `master` as the main branch of the repo for now. However, I think we should switch the main branch to `dev` and make all pull requests against `dev`, and treat `master` as "stable" going forward. Thoughts?

**Comment by erictheise** [comment]
@greatislander, no objections to adapting to house flow (`dev` and `master` branches). Would've started the project using those conventions had I known.

And yes, it's great that @gtirloni's on board and able to spin up a dev server & database and hopefully to have a cleaner way to pull production data into a local dev environment.

**Comment by colinbdclark** [comment]
That also makes sense to me, @greatislander.

**Comment by greatislander** [comment]
Thanks @erictheise and @colinbdclark for the feedback. I've updated the default branch to `dev` and changed the two open pull requests to be against `dev`. Over to @gtirloni for deploy configuration.

**Comment by greatislander** [comment]
Resolved in #79. `dev` is now deployed to [dev.directory.platform.coop](https://dev.directory.platform.coop).
