### ISSUE TITLE
Design & implement "full profile" for individuals

### ISSUE THREAD

**Issue by erictheise** [platform-coop-toolkit/coop-map-directory-index#7]
Our [wireframe](https://www.figma.com/file/tXFtpKPWuGUFrotFsXshZq/Directory-explorations_DA?node-id=174%3A4) features lots of links to __View full profile__. I think we'll need one design for organizations and one for individuals. This issue is for individuals.

This is even more of a moving target than the [organization full profile](https://github.com/platform-coop-toolkit/coop-map-directory-index/issues/6) as data for individuals isn't yet surfaced via the API and [account creation/user login](https://github.com/platform-coop-toolkit/coop-map-directory-index/issues/2) is still under development. But contact info, expertise, multiple social media handles/links, and "connections" are candidates for inclusion in a full profile.

It'd be great to have a basic layout to start iterating from @dayotte. Let's track it here.

**Comment by erictheise** [comment]
This Figma rookie just discovered the [Profile Page Explorations](https://www.figma.com/file/tXFtpKPWuGUFrotFsXshZq/Directory-explorations_DA?node-id=273%3A4) and sees that a lot has already been thought through. Catching up with these designs.

**Comment by erictheise** [comment]
@dayotte I've added some more data to [my record](https://demo.directory.platform.coop/individuals/1). You probably need to be logged in to see it.

For data we collect in `textarea`s I'm displaying _lorem ipsum_ if we have none or the actual text if we do. For individuals that would be the _Bio_ and _Notes_ fields.

**Comment by dayotte** [comment]
![Coop Founder Profile Page Mar 24 2020](https://user-images.githubusercontent.com/6207009/77469655-a78ccd00-6dcc-11ea-9314-601ba135d65d.png)

**Comment by erictheise** [comment]
![image](https://user-images.githubusercontent.com/317680/78332191-5ef7b100-753c-11ea-9a4d-70123886d762.png)

**Comment by erictheise** [comment]
@dayotte, questions.

There is always a `Next` and never a `Previous`. Should there be? If so, what is the placement?

The `Cancel` link at the bottom of every page; what does it do? Does the action depend on the page or is the action the same? Is the action to flush all collected information and redirect to the home page? To the first "Organization or Individual" page?

**Comment by dayotte** [comment]
> There is always a `Next` and never a `Previous`. Should there be? If so, what is the placement?

@erictheise there is a back button at the top left of each screen

**Comment by dayotte** [comment]
> The `Cancel` link at the bottom of every page; what does it do? Does the action depend on the page or is the action the same? Is the action to flush all collected information and redirect to the home page? To the first "Organization or Individual" page?

@erictheise this needs a warning dialog, which I will mock up. The action is the same from each page. Yes, it's action is to "flush all collected information and redirect to the home page".

**Comment by erictheise** [comment]
Wasn't there going to be a condensed version of this flow, ~2 steps instead of ~5? Mocks were never posted here.
