### ISSUE TITLE
New field for organizations: language

### ISSUE THREAD

**Issue by greatislander** [platform-coop-toolkit/coop-map-directory-index#72]
## Is your feature request related to a problem? Please describe.

We'd like to be able to reflect the language in which organizations operate.

## Describe the solution you'd like

The Language model should be attached to the Organization model.

## Describe alternatives you've considered

Not applicable.

## Additional context

Not applicable.

**Comment by erictheise** [comment]
This was done [in the User model](https://github.com/platform-coop-toolkit/coop-map-directory-index/blob/b3e118930db1b79f6863b56799b341924c3a48b5/accounts/models.py#L109), same approach should work for the Organization model where the `mdi.` will be unnecessary.
