### ISSUE TITLE
New field for organizations: contact phone

### ISSUE THREAD

**Issue by greatislander** [platform-coop-toolkit/coop-map-directory-index#73]
## Is your feature request related to a problem? Please describe.

We'd like to add an optional contact phone number for organizations.

## Describe the solution you'd like

The Organization model needs a new field for contact phone numbers.

## Describe alternatives you've considered

Not applicable.

## Additional context

We should consider using https://github.com/stefanfoulis/django-phonenumber-field.

**Comment by erictheise** [comment]
Odd. Oversight. Maybe the original `ioo.coop/directory` data grouped phone numbers with individual respondents as there is a `phone` field on User.
