### ISSUE TITLE
New field for organizations: worker distribution

### ISSUE THREAD

**Issue by greatislander** [platform-coop-toolkit/coop-map-directory-index#74]
## Is your feature request related to a problem? Please describe.

We'd like to reflect where workers are located within an organization:

- co-located
- nationally distributed
- internationally distributed

## Describe the solution you'd like

The Organization model needs a new field which allows one of these options to be chosen.

## Describe alternatives you've considered

Each organization already has address/geo fields. We considered adding multiple addresses/geo fields but we think it makes more sense for the address field to reflect the organization's business address (and mark its location on the map) and reflect the location of workers using the above approach.

## Additional context

Not applicable.

**Comment by erictheise** [comment]
If for any reason values for this field should track the values in the `geo_scope*` fields consider breaking these out of the `User` and `Organization` models and into a separate ManyToMany table.

In any case the list of options here has no `regionally distributed` option which seems to leave a gap; if workers are distributed across __the Midwest__ there's no way to capture that.
