### ISSUE TITLE
New field for organizations: number of members

### ISSUE THREAD

**Issue by greatislander** [platform-coop-toolkit/coop-map-directory-index#75]
## Is your feature request related to a problem? Please describe.

For some types of cooperatives, the number of members may be distinct from the number of workers (e.g. a multi-stakeholder, consumer cooperative may have both worker and consumer members). Reflecting the total number of members seems like it would be a valuable metric for reflecting the scale and scope of a cooperative alongside other existing metrics (impact and number of workers).

## Describe the solution you'd like

The Organization model should have a new field for number of members.

## Describe alternatives you've considered

Not applicable.

## Additional context

Not applicable.

**Comment by erictheise** [comment]
Question as to whether this should be an integer or ranges of integers.

Advantage: ranges should be easier for a profile manager to fill in, e.g. `20-49` shouldn't require the same level of thinking or lookup that "are we at 37 or 39?" does.

Disadvantage: aggregating over ranges requires using range midpoints. Ranges are lossy.

**Comment by greatislander** [comment]
@erictheise My feeling is that this should be an integer as membership records are closely tracked and should be readily available. I'm open to other opinions, though (cc: @dayotte @cherylhjli).

**Comment by erictheise** [comment]
If exact(ish) integers are easy to come by, @greatislander, by all means collect them.
